version: '3.8'

services:
  taskservice:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - app-net

networks:
  app-net:
